# Generated by Django 3.1.7 on 2021-03-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210318_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='用户名称'),
        ),
    ]
