# Generated by Django 3.1.7 on 2021-04-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='用户凭证'),
        ),
    ]
