# Generated by Django 3.1.7 on 2021-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210404_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='height',
            field=models.IntegerField(null=True, verbose_name='身高'),
        ),
    ]
