# Generated by Django 3.1.7 on 2021-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210411_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.CharField(max_length=64, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=64, null=True, verbose_name='联系电话'),
        ),
    ]
