# Generated by Django 3.1.7 on 2021-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210411_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_delete',
            field=models.IntegerField(default=1, verbose_name='逻辑删除'),
        ),
    ]
