# Generated by Django 3.1.7 on 2021-05-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_users_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='live',
            field=models.IntegerField(default=0, verbose_name='是否在线'),
        ),
    ]
