# Generated by Django 3.1.7 on 2021-05-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0012_auto_20210411_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='药品名称')),
            ],
            options={
                'verbose_name': '药品存储',
                'db_table': 'medicals',
            },
        ),
        migrations.CreateModel(
            name='Medicine_self',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='药品名称')),
                ('category', models.CharField(max_length=200, null=True, verbose_name='药品类别')),
                ('introduce', models.CharField(max_length=200, null=True, verbose_name='简介')),
                ('creat_data', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('suit', models.CharField(max_length=400, null=True, verbose_name='适应症状')),
                ('bad', models.CharField(max_length=400, null=True, verbose_name='不良症状')),
                ('life', models.IntegerField(verbose_name='保质期')),
                ('usemethod', models.CharField(max_length=400, null=True, verbose_name='使用方法')),
                ('taboo', models.CharField(max_length=200, null=True, verbose_name='禁忌')),
                ('heed', models.CharField(max_length=200, null=True, verbose_name='注意事项')),
                ('savemethod', models.CharField(max_length=200, null=True, verbose_name='保存方法')),
            ],
            options={
                'verbose_name': '程序自带药库',
                'db_table': 'medicine_self',
            },
        ),
        migrations.CreateModel(
            name='Medicine_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='药品名称')),
                ('category', models.CharField(max_length=200, null=True, verbose_name='药品类别')),
                ('introduce', models.CharField(max_length=200, null=True, verbose_name='简介')),
                ('creat_data', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('suit', models.CharField(max_length=200, null=True, verbose_name='适应症状')),
                ('bad', models.CharField(max_length=200, null=True, verbose_name='不良症状')),
                ('life', models.IntegerField(null=True, verbose_name='保质期')),
                ('use', models.CharField(max_length=200, null=True, verbose_name='使用方法')),
                ('taboo', models.CharField(max_length=200, null=True, verbose_name='禁忌')),
                ('heed', models.CharField(max_length=200, null=True, verbose_name='注意事项')),
                ('savemethod', models.CharField(max_length=200, null=True, verbose_name='保存方法')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='user.users', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户自己添加的药品',
                'db_table': 'medicine_user',
            },
        ),
        migrations.CreateModel(
            name='Medical_loads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='药品具体名字')),
                ('num', models.IntegerField(null=True, verbose_name='爬虫顺序')),
                ('img_url', models.CharField(max_length=200, null=True, verbose_name='图片地址')),
                ('suit', models.CharField(max_length=1000, null=True, verbose_name='适应症状')),
                ('usemethod', models.CharField(max_length=1000, null=True, verbose_name='使用方法')),
                ('lelment', models.CharField(max_length=200, null=True, verbose_name='成分')),
                ('bad', models.CharField(max_length=1000, null=True, verbose_name='不良反应')),
                ('err', models.CharField(max_length=200, null=True, verbose_name='禁忌')),
                ('heed', models.CharField(max_length=1000, null=True, verbose_name='注意事项')),
                ('savemethod', models.CharField(max_length=200, null=True, verbose_name='保存方法')),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='medicine.medicals', verbose_name='关联药品')),
            ],
            options={
                'verbose_name': '存储的药品们',
                'db_table': 'medical_loads',
            },
        ),
    ]
