# Generated by Django 3.1.7 on 2021-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='图片链接')),
                ('url1', models.CharField(max_length=200, verbose_name='url1')),
                ('url2', models.CharField(max_length=200, verbose_name='url2')),
                ('url3', models.CharField(max_length=200, verbose_name='url3')),
            ],
            options={
                'verbose_name': '图片链接',
                'db_table': 'img_urls',
            },
        ),
    ]
