# Generated by Django 3.1.7 on 2021-05-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_loads',
            name='translate',
            field=models.IntegerField(default=0, verbose_name='收藏标记位'),
        ),
    ]
